# Generated by Django 5.2.8 on 2025-11-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='parser',
            field=models.CharField(choices=[('GENERIC', 'Generic Syslog'), ('FORTINET', 'Fortinet')], default='GENERIC', max_length=50),
        ),
    ]
