# Generated by Django 5.2.8 on 2025-11-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_parser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='device',
            name='last_log_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='log_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='parser',
            field=models.CharField(choices=[('GENERIC', 'Generic Syslog'), ('FORTINET', 'Fortinet'), ('PALOALTO', 'Palo Alto')], default='GENERIC', max_length=50),
        ),
    ]
