# Generated by Django 5.2.8 on 2025-11-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_options_device_last_log_received_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='idx_device_status'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['ip_address'], name='idx_device_ip'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_log_received'], name='idx_device_last_log'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status', 'parser'], name='idx_device_status_parser'),
        ),
    ]
