# Generated by Django 5.2.8 on 2025-11-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_idx_device_status_device_idx_device_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='retention_days',
            field=models.PositiveIntegerField(choices=[(7, '7 days'), (14, '14 days'), (30, '30 days'), (60, '60 days'), (90, '90 days (default)'), (180, '180 days'), (365, '1 year'), (0, 'Forever (no auto-delete)')], default=90, help_text='Number of days to retain logs for this device. Set to 0 for unlimited retention.'),
        ),
    ]
